'use client';
import { Inter } from "next/font/google";
// import "./globals.css";
import MiniDrawer from "@/components/Sidebar/Bar";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [drawerOpen, setDrawerOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex" }}>
          <MiniDrawer
            open={drawerOpen}
            onOpen={() => setDrawerOpen(true)}
            onClose={() => setDrawerOpen(false)}
          />
          <div
            style={{
              flexGrow: 1,
              paddingLeft: drawerOpen ? 240 : 0,
              transition: "padding-left 0.3s ease",
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
